# Generated by Django 3.1.6 on 2021-02-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210208_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='game event', max_length=200),
            preserve_default=False,
        ),
    ]
